### ISSUE TITLE
Can't install cronjob

### ISSUE THREAD

**Issue by alexsuter** [axonivy-market/cronjob#3]
When installing cronjob via Axon Ivy Market in Axon Ivy Designer it fails.

This is because, there is a dropins-installer in product.json.

**Comment by majeed-hm** [comment]
Hi Alex,
What is a dropins-installer? I just configurred what is provided in the template.

**Comment by alexsuter** [comment]
installing a jar in dropins folder of designer. but you don't have one. your product.json is wrong, therefore you have errors when installing this product.

**Comment by majeed-hm** [comment]
Hi @alexsuter ,
I wanted to create a release with same version 10.0.3 but I am getting the following error message:
`Error: [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.0.0:deploy (default-deploy) on project cronjob: Failed to deploy artifacts: Could not transfer artifact com.axonivy.utils.cronjob:cronjob:pom:10.0.3 from/to github (https://maven.pkg.github.com/axonivy-market/cronjob): transfer failed for https://maven.pkg.github.com/axonivy-market/cronjob/com/axonivy/utils/cronjob/cronjob/10.0.3/cronjob-10.0.3.pom, status: 409 Conflict`
do I need to create a new release version? 10.0.4?

**Comment by alexsuter** [comment]
In a maven world you never release the same thing twice - there are caches all around the world (this artifact is already cached in CDN). Please create a new release -> 10.0.4

**Comment by majeed-hm** [comment]
Hi @alexsuter 
now it is working smoothly and we can close the issue.

**Comment by alexsuter** [comment]
thank you @majeed-hm 🥇
